package com.self.Exceptions

object Exception1 {

	var obj = new remoteCalculatorService()

	var sum = try{
		var sum = obj.add(3, 4)
		println(sum)
	}catch{
	  
	//case e: ServerIsDownException => log.error(e, "the remote calculator service is unavailable. should have kept your trusty HP.")
	
	case e: Exception => println(e, "the remote calculator service is unavailable.")
	
	} finally {
		obj.close()
	}
}